### ISSUE TITLE
`map` is weird.

### ISSUE THREAD

**Issue by meric** [meric/l2l#18]
Currently the `map` function in `itertools` module, calls the anonymous function with the value, as well as the index of the value.

So, when calling something like `(map + '(1 2 3 4))` it doesn't produce `'(1 2 3 4)` but rather `'(2 4 6 8)` because `map` is making `+` add the value as well as the index of the value together. 

Thoughts?

**Comment by technomancy** [comment]
I think this is fine; there is precedence for it in other langs. The only thing I can think of when it's a problem is these variadic math operators.

**Comment by meric** [comment]
Hmm, what if I remove the second argument map's anonymous function, and add an `each` function that is exactly the same as the current map? I imagine if the user wanted to write, say, a matrix multiplication operator, or any other variadic function, they'll meet the similar problem and have to write something like `(map (lambda (x) (myvariadicfunc x)) iterable)` which IMO is cumbersome compared to `(map myvariadicfunc iterable)`. Or should the `each` be the single argument version?

**Comment by technomancy** [comment]
Actually yeah, I thought of a good reason to move the second arg to a different function. Some lisps have variadic map like this: `(map + '(1 2 3) '(4 5 6)) ; -> (5 7 9)`

In this case the function gets one arg for each list that's passed into `map`. If `map` gives an index arg then it interferes with this improved functionality.

Ruby uses `map` and `map_with_index`, but I'm not opposed to `each` being the one that passes an index in.

**Comment by technomancy** [comment]
One other thing that would be very helpful is a uniform API to access all collection data types. I know they are all just tables underneath, but it's very useful in Clojure and Racket to have a single interface that lets you walk through a collection of any type instead of proliferating all the iteration forms for each compound data type.

* http://docs.racket-lang.org/reference/sequences.html
* http://clojure.org/sequences

Lua does something similar with iterators; even though there is only one compound data type, using `pairs` or `ipairs` lets you use the same API with k/v tables vs arrays. I wonder if we could do something similar to that for lists?

**Comment by meric** [comment]
Renamed `map` to `each`. The new `map` does not provide index argument.

Next up, implement variadic map.

Currently the `list` and `vector` both work with ipairs. What other interfaces would such an API have?

**Comment by technomancy** [comment]
> Currently the list and vector both work with ipairs. What other interfaces would such an API have?

I'm thinking more about exposing a generic interface within lisp rather than using pairs/ipairs directly, though perhaps having an lpairs (which would iterate through successive car values) would make sense when using lisp values from lua.

Having a set of iteration macros like Racket's `for` would be great:

  http://docs.racket-lang.org/reference/for.html

In particular `for` for side-effects, `for/list` for turning any type into a list, `for/vector` for turning any into a vector, and `for/table`. Including `for/fold` might be nice too, but the others on that page are more specialized and maybe aren't needed early on.

Thoughts?

**Comment by technomancy** [comment]
Speaking of which, is there a way to get multiple values back from a function? Maybe this could be documented in the "Differences from other lisps" section.

**Comment by meric** [comment]
Yes, e.g.  `(vector (unpack (vector 1 2 3)))`. The repl didn't support multiple returns that didn't get wrapped by a table, but with the latest commit, it does. Also added an `id` function to allow defining l2l functions that return multiple values. E.g.

`echo "((lambda () (id 1 2 3 4)))" | ./l2l`

**Comment by meric** [comment]
On the topic of the iteration macros - Let me try to understand this - currently we have the `each` function that always returns a list. If we want a uniform `map` API across all data types, we'd have `each/list`, `each/vector` and `each/dict`, all of them work through the standard ipairs or pairs interface? I'm taking a look at the `for` macro...

**Comment by technomancy** [comment]
Right; actually as I think of it now we can't do generic functionality exactly the same as Racket, because Racket can know the type at runtime simply by looking at the data structure, while for us it's always going to be a table.

So we would need the programmer to indicate the input type, just like how you need to choose between pairs/ipairs in Lua. I suppose that could lead to an awkward set of combinations: for/list/list, for/list/table, for/vector/list, etc. where the macro name includes the input and output type.

Anyway, all that to say the problem is not quite as straightforward as I was thinking. Maybe this is just something to keep in mind for future APIs.

**Comment by meric** [comment]
In the `rewrite` branch, map is `vector.cast` and `list.cast`.

**Comment by technomancy** [comment]
Why don't you put a note in the readme on `master` letting people know all development is happening on the `rewrite` branch?

**Comment by meric** [comment]
Done. :)

https://github.com/meric/l2l/blob/master/README.md#notice

```
Notice

This branch is deprecated.

When the rewrite branch is ready, this master branch will be tagged and replaced with it.
```

**Comment by technomancy** [comment]
thanks!
