### ISSUE TITLE
Replace reader.read_execute with compiler.loadstring

### ISSUE THREAD

**Issue by technomancy** [meric/l2l#19]
Having the reader responsible for evaluation doesn't make any sense.

What about trying to keep the API for loading code as similar to that of Lua as possible? Adding `load`, `loadstring`, and `loadfile` which return chunk functions would make it more consistent.

**Comment by technomancy** [comment]
If we do this right it might let us use Lua's built-in sandboxing (`setfenv`, etc on the chunk returned from `loadstring`) instead of reinventing the wheel on our own.

**Comment by meric** [comment]
read_execute is an imitation of the Common Lisp "#." read macro. 

See the `(print (#. (factorial 10)))` example in http://rosettacode.org/wiki/Compile-time_calculation.

Here's a case where I think it can be useful. Normally if you're executing the same form `(do ....)`, any modifications to the read macro won't affect the form. If, however, we have the #. operator, then `(do #.(modify read macro table), xxyyyzz)` then parsing xxyyyzz will be affected by the changes caused by `#.(modify read macro table)`.

I do think it's like an esoteric edge case, but it must have been in Common Lisp for some reason so I've imitated it in l2l.

I think creating an API mirroring's lua's `load`, `loadstring`, etc, are good idea.

**Comment by technomancy** [comment]
I see; I think I understand when you put it this way.

Be aware that this is a common source of security problems both in Clojure and CL; most people expect the reader to be completely safe and don't think twice to run untrusted user input through the reader. It can be a nice feature to have, but I would consider making it opt-in instead of turning it on by default.

But yeah, anyway, having a lualike API for loading should be a separate issue.

**Comment by meric** [comment]
Good idea, let's make it opt-in and work towards the lualike API for evaluating strings.

**Comment by meric** [comment]
Moved read_execute into an option. (088a0982376d81a0a1b1f18aa22fbeee5dfe9460)
