### ISSUE TITLE
is it a subset of clojure ?

### ISSUE THREAD

**Issue by zaxebo1** [meric/l2l#35]
this is actually a query and issue?
I would request that l2l syntax be a strict **subset** of clojure. That is (when not accessing lua api or jvm api), the every valid l2l program will be a valid clojure program, but reverse may not be  true.

in that case, there will be a real practical benefit of porting our small programs to l2l

**Comment by meric** [comment]
Hi, I've been working on a parser combinator that will allow mixing lisp and lua in the same program, and I've been working on improving the performance of the parser. I will consider making the lisp part a subset of Clojure, it sounds like a good idea. 

Right now l2l isn't usable production, IMO. I'm still working on it.

**Comment by technomancy** [comment]
This request as stated is more or less incompatible with the project as
it stands now--at the very least because Clojure is strongly oriented
around the seq abstraction, while Lua has only tables and requires you
to choose at iteration time whether your data structure should be
treated as sequential or associative.

Right now l2l is quite lightweight, and maybe I'm putting words in
@meric's mouth, but I believe the intention is to stay as close to Lua
semantics as possible and not introduce new concepts beyond the minimum
of what's necessary for a lisp.

The idea of having a lisp where you can take small portable snippets of
Clojure code and just expect it to run is interesting, but it seems
different from what we currently have. It would be wonderful to add
things like destructuring, map syntax for tables, and maybe even pattern
matching, all which could be added without any runtime overhead, but I'm
a bit wary of radically altering the semantics from the underlying
platform.

@meric: it might be helpful if you could clarify whether you mean simply
altering the syntax or whether you're considering making more sweeping
semantic changes.

**Comment by meric** [comment]
It *might* be nice to match the syntax of l2l with clojure where it's straightforward to implement and does not detract from lua semantics.

Clojure:
```
(defn do-something [x y & more] ... )
```

l2l:
```
(defun ! (n) 
  (cond (== n 0) 1
        (== n 1) 1
        (* n (! (- n 1)))))
```

I am willing to consider little changes like renaming the keywords and names like `defun` to `defn`. I am less likely to consider changes like changing varargs from `...` to `& more` and destructuring. It would depend on whether those concepts map directly to Lua in a straightforward way, or not. I would first explore whether I can create a turing-complete, useful subset of clojure this way, and then decide whether it's worth doing. The main concern is to maximise performance to match the equivalent Lua. A lisp that's 10x less performant than Lua is substantially less useful than a lisp that's 1x or 2x less performant.

It will most definitely not be true where every l2l program will be a valid clojure program. For example, a l2l program may make use of Lua coroutines, which is not implemented in any Clojure dialect.

**Comment by zaxebo1** [comment]
:+1:
Thanks a lot for consideration  :smile:

**Comment by zaxebo1** [comment]
Also, some official way for the programs to **detect** that they are running inside clojure or running inside l2l, will be helpful.

 Because then with help of this detection, one can take appropriate measures in single source code wherever some library function exists in clojure, but not exists in l2l

**Comment by meric** [comment]
I've decided to move l2l further into Lua interoperability.

It means one can mix Lua and Lisp code however many levels deep.

Example.

```
-- Install quote and quasiquote read macro and special forms.

(-# LANGUAGE l2l.contrib.quote #-)
(-# LANGUAGE l2l.contrib.quasiquote #-)

-- Semicolons have no effect.
;;;

-- Escape into Lua with backslash.
-- When using Lua statements ending with parenthesis, use semicolon at the end,
-- so the compiler doesn't think any lisp statements after as being another
-- function call.

\print(1);
\print(1 --[[This is a Lua multiline comment]]);
(print "this line is not turned into print(...)(...)")

-- Normal Lisp statements.
(print "hello world")

-- Using the LANGUAGE extensions.
(print '(1 2 3))
(print `(1 (1) ,(print 1 2)))

-- Use Lua expressions in Lisp S-Expressions with backslash.
(print \function(x) print(x, \'(1 2 3 (a 1) \b(1))) end)

(print \{a=1, b=2, 3, 4} \function()
    for i=1, 3 do print(i) end return 9
end)
```

**Comment by technomancy** [comment]
I like the idea a lot.

However, I'm very confused as to the reason why something as fundamental as quote and quasiquote are implemented as extensions. Could you shed some light on this?

**Comment by meric** [comment]
Good point. My plan is to wrap it all up so all one has to do is `(-# LANGUAGE l2l.core #-)` to load all the features... Could even make it part of the default header. just found it improved my own code a lot if I separated out this way.

**Comment by technomancy** [comment]
I see. Is this inspired by racket's #lang directives? It can be nice to be able to declare a smaller subset (#lang racket/base) if you want to save memory or something, as long as the default has everything you typically need.

**Comment by meric** [comment]
I'm ashamed to say, it's inspired by how babeljs comes with absolutely nothing without extensions. :)

The lisp is operational even without quote and quasi quote because one could theoretically escape into Lua and build the abstract syntax tree using Lua instead of lisp.

I think the main advantage is one can now write lisp macros that expand into Lua - l2l becoming a superset of Lisp and Lua, implemented in Lua itself. 

Take a look at https://github.com/meric/l2l/blob/rewrite/l2l/macro/math.lisp, implementation of the + macro.
